<MainWindow>:
    BoxLayout:
        id: main_box
        orientation: "vertical"
        BoxLayout:
            id: title
            Label: 
                text: "primo form"
        BoxLayout:
            id: fields
            orientation: "vertical"
            BoxLayout:
                Label:
                    text: "Name"
                TextInput:
            BoxLayout:
                Label:
                    text: "Surname"
                TextInput:
            BoxLayout:
                Label:
                    text: "City"
                TextInput:
            BoxLayout:
                Label:
                    text: "Date"
                TextInput:
        BoxLayout:
            id: buttons
            Button:
                text: "Send"
