
#Commenti a caso:
# MainWindow: Finestra principale
# BoxLayout: Box orizzontale/verticale che contiene gli altri elementi (altri box, testo,bottoni ecc)
# 
# i BoxLayout vuoti servono per separare gli elementi 

# Classe custom per la label
# @QUALCOSA per ereditare le funzionalità della classe 
# In questo caso specifico solo il colore, per non ripeterlo in tutti i widget
<CustomLabel@Label>:
    color: 0,0,0,1

<TitleLabel@Label>:
    canvas.before:
        Color:
            rgba: 1,0.5,0,1
        Rectangle:
            size: self.size
            pos: self.pos
    color: 1,1,1,1




<MainWindow>:
# per rendere visibili i widget al file python
    sub: sub
    input_name: input_name
    input_surname: input_surname
    input_age: input_age
    input_city: input_city


# Corpo effettivo della finestra
    BoxLayout:
        id: main_box
        orientation: "vertical"
        BoxLayout:
            id: title
            size_hint_y: 0.20
            TitleLabel: 
                text: "primo form"
                font_size: 40
                bold: True
        BoxLayout:
            id: fields
            canvas.before:
                Color:
                    rgba: 0.388,0.4,0.415,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            orientation: "vertical"
            BoxLayout:
            BoxLayout:
                size_hint_y: None
                height: 30
                Label:
                    text: "Name"
                    color: [0,0,0,1]
                TextInput:
                    id: input_name
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:
                    text: "Surname"
                TextInput:
                    id: input_surname
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:                   
                    text: "City"
                TextInput:
                    id: input_city
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:                   
                    text: "Date"
                TextInput:
                    id: input_age
                    multiline: False
            BoxLayout:
        BoxLayout:
            id: buttons
            size_hint_y: 0.1 
            BoxLayout:
            Button:
                id: sub
                background_normal: ""
                background_color: 1,0.5,0,1
                background_down: ""
                text: "Send"
                on_press:
                    self.background_color = 0,0,1,0.8
                on_release:
                    self.background_color = 1,0.5,0,1
                    root.pop_form()

            BoxLayout:


<Mypopup>:
    send_form: send_form 
    id: popup
    size_hint: 0.5,0.5
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Send form?"
            color: [1,1,1,1]
            font_size: 20
        BoxLayout:
            orientation: "horizontal"
            Button:
                id : send_form
                size_hint_y: None
                height: 50
                text: "Confirm"
                on_release:
                    root.send_form()
                    root.dismiss()
            Button:
                size_hint_y: None
                height: 50
                text: "Cancel"
                on_press:
                    root.dismiss()
