
#Commenti a caso:
# MainWindow: Finestra principale
# BoxLayout: Box orizzontale/verticale che contiene gli altri elementi (altri box, testo,bottoni ecc)
# 
# i BoxLayout vuoti servono per separare gli elementi 

# Classe custom per la label
# @QUALCOSA per ereditare le funzionalità della classe 
# In questo caso specifico solo il colore, per non ripeterlo in tutti i widget

<CustomLabel@Label>:
    color: 0,0,0,1

<TitleLabel@Label>:
    canvas.before:
        Color:
            rgba: 1,0.5,0,1
        Rectangle:
            size: self.size
            pos: self.pos
    color: 1,1,1,1




<MainWindow>:
 # per rendere visibili i widget al file python
    sub: sub
    input_name: input_name
    input_surname: input_surname
    input_age: input_age
    input_day: input_day
    input_month: input_month
    input_year: input_year
    input_city: input_city
    input_job: input_job


 # Corpo effettivo della finestra
    BoxLayout:
        padding: 10,10
        id: main_box
        orientation: "vertical"
        BoxLayout:
            id: title
            size_hint_y: 0.20
            TitleLabel: 
                text: "primo form"
                font_size: 40
                bold: True
        BoxLayout:
            padding: 10,10
            id: fields
            canvas.before:
                Color:
                    rgba: 0.388,0.4,0.415,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            orientation: "vertical"
            BoxLayout:
                size_hint_y: None
                height: 30
                Label:
                    text: "Name"
                    color: [0,0,0,1]
                TextInput:
                    id: input_name
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:
                    text: "Surname"
                TextInput:
                    id: input_surname
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:                   
                    text: "City"
                TextInput:
                    id: input_city
                    multiline: False
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:                   
                    text: "Date"
                BoxLayout:
                    id: input_age
                    orientation: "horizontal"
                    height: 30
                    Spinner:
                        id: input_day
                        multiline: False
                        text: "Day"
                        values: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"]
                    Spinner:
                        id: input_month
                        multiline: False
                        text: "Month"
                        values: ["January","February","March","April","May","June","July","August","September","October","November","December"]
                    Spinner:
                        id: input_year
                        multiline: False
                        text: "Year"   
                        values: 
            BoxLayout:
                size_hint_y: None
                height: 30
                CustomLabel:                   
                    text: "Job"
                Spinner:
                    id: input_job
                    text: "choose"
                    values: ["Student", "Teacher", "Doctor", "Other"]
                    size_hint_y: None
                    height: 30            
            BoxLayout:
        BoxLayout:
            id: buttons
            size_hint_y: 0.1 
            canvas.before:
                Color:
                    rgba: 0.388,0.4,0.415,1
            BoxLayout:
            Button:
                id: sub
                background_normal: ""
                background_color: 1,0.5,0,1
                background_down: ""
                text: "Send"
                on_press:
                    self.background_color = 0,0,1,0.8
                on_release:
                    self.background_color = 1,0.5,0,1
                    root.pop_form()

            BoxLayout:




<Mypopup>:
    send_form: send_form 
    id: popup
    size_hint: 0.5,0.5
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Send form?"
            color: [1,1,1,1]
            font_size: 20
        BoxLayout:
            orientation: "horizontal"
            Button:
                id : send_form
                size_hint_y: None
                height: 50
                text: "Confirm"
                on_release:
                    root.send_form()
                    root.dismiss()

            Button:
                size_hint_y: None
                height: 50
                text: "Cancel"
                on_press:
                    root.dismiss()


<SecondWindow>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Second screen"
            color: [1,1,1,1]
            font_size: 90
        Button:
            text: "Back"
            on_release:
                root.go_back()
            size_hint_y: 0.1