
#Commenti a caso:
# MainWindow: Finestra principale
# BoxLayout: Box orizzontale/verticale che contiene gli altri elementi (altri box, testo,bottoni ecc)
# 
# i BoxLayout vuoti servono per separare gli elementi 

# Classe custom per la label
# @QUALCOSA per ereditare le funzionalità della classe 
# In questo caso specifico solo il colore, per non ripeterlo in tutti i widget

<CustomLabel@Label>:
    color: 0,0,0,1

<TitleLabel@Label>:
    canvas.before:
        Color:
            rgba: 1,0.5,0,1
        Rectangle:
            size: self.size
            pos: self.pos
    color: 1,1,1,1

<CustomButton@Button>:
    background_color: 1,0.5,0,1

<CustomBox@BoxLayout>:
    size_hint_y: None
    height: 30    

#-----------------------------------------------------------------------------------------------------------------------

<MainWindow>:
 # per rendere visibili i widget al file python
    sub: sub
    input_name: input_name
    input_surname: input_surname
    input_age: input_age
    input_day: input_day
    input_month: input_month
    input_year: input_year
    input_city: input_city
    input_job: input_job
    license_a: license_a
    license_b: license_b
    license_c: license_c


 # Corpo effettivo della finestra
    BoxLayout:
        canvas.before:
            Color:
                rgba: 0.388,0.4,0.415,1
        padding: 10,10
        id: main_box
        orientation: "vertical"
        BoxLayout:
            id: title
            size_hint_y: 0.20
            TitleLabel: 
                text: "primo form"
                font_size: 40
                bold: True
        BoxLayout:
            padding: 20
            spacing: 10
            id: fields
            canvas.before:
                Color:
                    rgba: 0.388,0.4,0.415,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            orientation: "vertical"
            CustomBox:
                Label:
                    text: "Name"
                    color: [0,0,0,1]
                TextInput:
                    id: input_name
                    multiline: False
            CustomBox:
                CustomLabel:
                    text: "Surname"
                TextInput:
                    id: input_surname
                    multiline: False
            CustomBox:
                CustomLabel:                   
                    text: "City"
                TextInput:
                    id: input_city
                    multiline: False
            CustomBox:
                CustomLabel:                   
                    text: "Date"
                CustomBox:
                    id: input_age
                    orientation: "horizontal"
                    Spinner:
                        id: input_day
                        multiline: False
                        background_normal: ""
                        background_color: 1,0.5,0,1
                        text: "Day"
                        values: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"]
                    Spinner:
                        id: input_month
                        multiline: False
                        background_normal: ""
                        background_color: 1,0.5,0,1
                        text: "Month"
                        values: ["January","February","March","April","May","June","July","August","September","October","November","December"]
                    Spinner:
                        id: input_year
                        multiline: False
                        background_normal: ""
                        background_color: 1,0.5,0,1
                        text: "Year"   
                        values: ["1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020"]
            CustomBox:
                CustomLabel:                   
                    text: "Job"
                Spinner:
                    id: input_job
                    background_normal: ""
                    background_color: 1,0.5,0,1
                    text: "choose"
                    values: ["Student", "Teacher", "Doctor", "Other"]
                    size_hint_y: None
                    height: 30      
            CustomBox:     
                CustomLabel:
                    text: "Driver's license"
                BoxLayout:
                    CustomLabel:
                        text: "License A"
                    CheckBox:
                        id: license_a
                        color: [0,0,0,1]
                    CustomLabel:
                        text: "License B"
                    CheckBox:
                        id: license_b
                        color: [0,0,0,1]
                    CustomLabel:
                        text: "License C"
                    CheckBox:
                        id: license_c
                        color: [0,0,0,1]                                        
            BoxLayout:

        CustomBox:
            id: buttons
            canvas.before:
                Color:
                    rgba: 0.388,0.4,0.415,1
            BoxLayout:
            CustomButton:
                id: sub
                background_normal: ""
                background_color: 1,0.5,0,1
                background_down: ""
                text: "Send"
                on_press:
                    self.background_color = 0,0,1,0.8
                on_release:
                    self.background_color = 1,0.5,0,1
                    root.pop_form()
            BoxLayout:


#-----------------------------------------------------------------------------------------------------------------------

<Mypopup>:
    send_form: send_form 
    id: popup
    size_hint: 0.5,0.5
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Send form?"
            color: [1,1,1,1]
            font_size: 20
        BoxLayout:
            orientation: "horizontal"
            CustomButton:
                id : send_form
                size_hint_y: None
                height: 50
                text: "Confirm"
                on_release:
                    root.send_form()
                    root.dismiss()

            CustomButton:
                size_hint_y: None
                height: 50
                text: "Cancel"
                on_press:
                    root.dismiss()

#-----------------------------------------------------------------------------------------------------------------------

<SecondWindow>:
    name: "second_window" 
    BoxLayout:
        canvas.before:
            Color:
                rgba: 0.388,0.4,0.415,1
            Rectangle:
                size: self.size
                pos: self.pos
        orientation: "vertical"
        Label:
            text: "Thanks for filling the form"
            color: [1,1,1,1]
            font_size: 40
        BoxLayout:
            spacing: 10
            padding: 10
            orientation: "horizontal"
            CustomButton:
                size_hint_y: None
                height: 50
                text: "Back"
                on_release:
                    root.go_back()
            CustomButton:
                size_hint_y: None
                height: 50            
                text: "exit"
                on_release:
                    exit()

#-----------------------------------------------------------------------------------------------------------------------